### ISSUE TITLE
Validar que la tabla de la DB se encuentre creada ante un alta de usuario

### ISSUE THREAD

**Issue by seguijoaquin** [seguijoaquin/taller2-sharedserver#4]
Se debería validar que la tabla users de la base de datos se encuentre creada ante el alta de un nuevo usuario.

**Comment by diegokim** [comment]
La validacion se hace a la hora de hacer la query, si no existe la tabla tiraba un error pero quedaba colgado el servidor, ahora lo que hace es lanzar el error, loguear y ademas finalizar la conexion y mandar codigo 400 al app server
