### ISSUE TITLE
Modificación de la estructura de la DB para facilitar consultas

### ISSUE THREAD

**Issue by seguijoaquin** [seguijoaquin/taller2-sharedserver#7]
Modificar la estructura de la base de datos de Postgre, que es de tipo:
- id SERIAL PRIMAL KEY
- data JSON

Por una estructura de varias columnas, donde cada columna sea un atributo distinto, para aprovechar las consultas SQL.

Estructura tabla usuarios:
- id: serial primal key
- name: string
- alias: string
- email: string
- latitude: float
- longitude: float

Estructura tabla intereses:
- id_usuario: int
- categoria: enum o string
- valor: string

**Comment by diegokim** [comment]
Se cambio la estrutura de la base de datos desde el cliente de heroku.

Falta agregar tabla de intereses.
